app/models.py
from app import db
from datetime import datetime

class Submission(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    reddit_id = db.Column(db.String(7), unique=True)
    reddit_link = db.Column(db.String(100), unique=True)
    title = db.Column(db.Text)
    created_at = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    offer = db.relationship("Offer", back_populates="submission")
    status = db.Column(db.String(10), index=True)

    def __repr__(self):
      return '<{}>'.format(self.title)

class Offer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(8), index=True)
    symbol = db.Column(db.String(8), index=True)
    qty = db.Column(db.Integer)
    price = db.Column(db.Float)
    submission_id = db.Column(db.String(7), db.ForeignKey('submission.reddit_id'))
    submission = db.relationship("Submission", back_populates="offer", uselist=False)

    def __repr__(self):
      return '<{} {} - ${} x {}>'.format(self.type, self.symbol, self.price, self.qty)

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_moment import Moment

import logging
from logging.handlers import RotatingFileHandler
import os

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
bootstrap = Bootstrap(app)
moment = Moment(app)

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    #login.init_app(app)
    #mail.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    #babel.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    #from app.auth import bp as auth_bp
    #app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug:
        if app.config['LOG_TO_STDOUT']:
            app.logger = logging.getLogger()
            app.logger.setLevel(logging.INFO)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/gcx.log', maxBytes=10240,
                                               backupCount=10)
            file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

            app.logger.setLevel(logging.INFO)
            app.logger.info('GCX startup')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app import db
from app.models import Submission, Offer
from datetime import datetime,timedelta
from app.main import bp

@bp.route('/')
@bp.route('/index')
def index():
    query = db.session.query(Offer.symbol.distinct().label("symbol"))
    symbols = [row.symbol for row in query.all()]
    gcs = []
    for symbol in symbols:
        try:
            bid = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).first()
            ask = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).first()
            price = (bid.price * bid.qty + ask.price * ask.qty)/(bid.qty + ask.qty)
            #vol = Offer.query.filter_by(symbol=symbol).count()
            vol =  db.session.query(Offer).filter_by(symbol=symbol).join(Submission).filter(Submission.created_at.between(datetime.utcnow() - timedelta(hours=24), datetime.utcnow())).count()
            gc = {"symbol": symbol, "bid": bid.price, "ask": ask.price, "volume": vol, "price": price}
            gcs.append(gc)
        except:
            pass

    return render_template('index.html', title='Home', gcs = gcs)

@bp.route('/<symbol>')
def gc(symbol):
    symbol = symbol.upper()
    #bid = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).first()
    recentBids = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    recentAsks = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    #ask = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).first()
    latestBid = recentBids[0]
    latestAsk = recentAsks[0]
    price = (latestBid.price * latestBid.qty + latestAsk.price * latestAsk.qty)/(latestBid.qty + latestAsk.qty)
    #vol = Offer.query.filter_by(symbol=symbol).count()
    vol = db.session.query(Offer).filter_by(symbol=symbol).join(Submission).filter(Submission.created_at.between(datetime.utcnow() - timedelta(hours=24), datetime.utcnow())).count()

    return render_template('gc.html', gc = gc, bid = latestBid, ask = latestAsk, symbol = symbol, vol = vol, price = price, bids = recentBids, asks=recentAsks, title=symbol)

@bp.route('/about')
def about():
    return render_template('about.html', title='About')

@bp.route('/legal')
def legal():
    return render_template('legal.html', title='Legal')

app/routes.py
from flask import render_template
from app import app, db
from app.models import Submission, Offer
from datetime import datetime,timedelta

@app.route('/')
@app.route('/index')
def index():
    query = db.session.query(Offer.symbol.distinct().label("symbol"))
    symbols = [row.symbol for row in query.all()]
    gcs = []
    for symbol in symbols:
        try:
            bid = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).first()
            ask = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).first()
            price = (bid.price * bid.qty + ask.price * ask.qty)/(bid.qty + ask.qty)
            #vol = Offer.query.filter_by(symbol=symbol).count()
            vol =  db.session.query(Offer).filter_by(symbol=symbol).join(Submission).filter(Submission.created_at.between(datetime.utcnow() - timedelta(hours=24), datetime.utcnow())).count()
            gc = {"symbol": symbol, "bid": bid.price, "ask": ask.price, "volume": vol, "price": price}
            gcs.append(gc)
        except:
            pass

    return render_template('index.html', title='Home', gcs = gcs)

@app.route('/<symbol>')
def gc(symbol):
    symbol = symbol.upper()
    #bid = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).first()
    recentBids = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    recentAsks = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    #ask = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).first()
    latestBid = recentBids[0]
    latestAsk = recentAsks[0]
    price = (latestBid.price * latestBid.qty + latestAsk.price * latestAsk.qty)/(latestBid.qty + latestAsk.qty)
    #vol = Offer.query.filter_by(symbol=symbol).count()
    vol = db.session.query(Offer).filter_by(symbol=symbol).join(Submission).filter(Submission.created_at.between(datetime.utcnow() - timedelta(hours=24), datetime.utcnow())).count()

    return render_template('gc.html', gc = gc, bid = latestBid, ask = latestAsk, symbol = symbol, vol = vol, price = price, bids = recentBids, asks=recentAsks)

@app.route('/<symbol>/bids')
def bids(symbol):
    symbol = symbol.upper()
    bids = db.session.query(Offer).filter_by(symbol=symbol, type="bid").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    return render_template('bids.html', symbol = symbol, bids = bids)

@app.route('/<symbol>/asks')
def asks(symbol):
    symbol = symbol.upper()
    asks = db.session.query(Offer).filter_by(symbol=symbol, type="ask").join(Submission).order_by(Submission.created_at.desc()).limit(10).all()
    
    return render_template('asks.html', symbol = symbol, asks = asks)

@app.route('/about')
def about():
    return render_template('about.html', title='About')

@app.route('/legal')
def legal():
    return render_template('legal.html', title='Legal')

app/templates/_asks.html
<table class="table table-striped">
    <tr>
        <th>ask</th>
        <th>status</th>
        <th>timestamp</th>
    </tr>
    {% for ask in asks %}
    <tr>
        <td><a href="https://old.reddit.com{{ ask.submission.reddit_link }}">${{ '{0:.2f}'.format(ask.price) }} x {{ '{}'.format(ask.qty) }}</a></td>
        <td>{{ ask.submission.status }}</td>
        <td>{{ moment(ask.submission.created_at).fromNow() }}</td>
    </tr>
    {% endfor %}
</table>

app/templates/_bids.html
<table class="table table-striped">
    <tr>
        <th>bid</th>
        <th>status</th>
        <th>timestamp</th>
    </tr>
    {% for bid in bids %}
    <tr>
        <td><a href="https://old.reddit.com{{ bid.submission.reddit_link }}">${{ '{0:.2f}'.format(bid.price) }} x {{ '{}'.format(bid.qty) }}</a></td>
        <td>{{ bid.submission.status }}</td>
        <td>{{ moment(bid.submission.created_at).fromNow() }}</td>
    </tr>
    {% endfor %}
</table>

app/templates/about.html
{% extends "base.html" %}
{% block app_content %}
<p>GCXWatch scrapes the popular <a href="https://old.reddit.com/r/giftcardexchange">r/giftcardexchange</a> subreddit and attempts to apply common stock market thinking to the trading of giftcards.</p>
<p>For definitions, see:</p>
<ul>
    <li><a href="https://www.investopedia.com/terms/b/bid.asp">bid</a></li>
    <li><a href="https://www.investopedia.com/terms/a/ask.asp">ask</a></li>
    <li><a href="https://www.investopedia.com/terms/v/volume.asp">volume</a></li>
</ul>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-HR6JKELV4K"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-HR6JKELV4K');
	</script>
{% endblock %}

{% block title %}
    {% if title %}{{ title }} - GCXWatch{% else %}Welcome to GCXWatch{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">GCXWatch</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.about') }}">About</a></li>
                    <li><a href="{{ url_for('main.legal') }}">Legal</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/gc.html
{% extends "base.html" %}

{% block app_content %}
    <div class="container-fluid">
        <div class="row">
            <h1>${{ symbol }} - ${{ '{0:.2f}'.format(price) }}</h1>
        </div>
          <div class="row">
            <div class="col-md-6">
              {% include '_bids.html' %}
            </div>
            <div class="col-md-6">
              {% include '_asks.html' %}
            </div>
          </div>
    </div>
    
    
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>GCs</h1>
    <hr>
    <table class="table table-striped">
        <tr>
            <th>symbol</th>
            <th>price (per $ of face value)</th>
            <th>bid</th>
            <th>ask</th>
            <th>volume (prev. 24 hours)</th>
        {% for gc in gcs %}
        <tr>
            <td><a href="{{ url_for('main.gc', symbol=gc.symbol) }}">{{ gc.symbol }}</a></td>
            <td>${{ '{0:.2f}'.format(gc.price) }}</td>
            <td>${{ '{0:.2f}'.format(gc.bid) }}</td>
            <td>${{ '{0:.2f}'.format(gc.ask) }}</td>
            <td>{{ gc.volume }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/legal.html
{% extends "base.html" %}
{% block app_content %}
<p>GCXWatch is for your entertainment and educational purposes only. Opinions expressed on this site are that of their owners and should not be considered as financial or investing advice.</p>
<p>GCXWatch is not a market maker. No gift cards are bought or sold on this site.</p>
{% endblock %}